export const AD_LIST_REQUEST = 'AD_LIST_REQUEST';
export const AD_LIST_SUCCESS = 'AD_LIST_SUCCESS';
export const AD_LIST_FAIL = 'AD_LIST_FAIL';


export const FILTER_BUSINESS_REQUEST = 'FILTER_BUSINESS_REQUEST';
export const FILTER_BUSINESS_SUCCESS = 'FILTER_BUSINESS_SUCCESS';
export const FILTER_BUSINESS_FAIL = 'FILTER_BUSINESS_FAIL';

export const AD_PROFILE_REQUEST = 'AD_PROFILE_REQUEST';
export const AD_PROFILE_SUCCESS = 'AD_PROFILE_SUCCESS';
export const AD_PROFILE_FAIL = 'AD_PROFILE_FAIL';

export const OPEN_MESSAGE_REQUEST = 'OPEN_MESSAGE_REQUEST';
export const OPEN_MESSAGE_SUCCESS = 'OPEN_MESSAGE_SUCCESS';
export const OPEN_MESSAGE_FAIL = 'OPEN_MESSAGE_FAIL';

export const FETCH_MESSAGE_REQUEST = 'FETCH_MESSAGE_REQUEST';
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS';
export const FETCH_MESSAGE_FAIL = 'FETCH_MESSAGE_FAIL';

export const SEND_CONTACT_FORM_REQUEST = 'SEND_CONTACT_FORM_REQUEST';
export const SEND_CONTACT_FORM_SUCCESS = 'SEND_CONTACT_FORM_SUCCESS';
export const SEND_CONTACT_FORM_FAIL = 'SEND_CONTACT_FORM_FAIL';

export const DELETE_AD_PROFILE_REQUEST = 'DELETE_AD_PROFILE_REQUEST';
export const DELETE_AD_PROFILE_SUCCESS = 'DELETE_AD_PROFILE_SUCCESS';
export const DELETE_AD_PROFILE_FAIL = 'DELETE_AD_PROFILE_FAIL';

export const USER_ADS_REQUEST = 'USER_ADS_REQUEST';
export const USER_ADS_SUCCESS = 'USER_ADS_SUCCESS';
export const USER_ADS_FAIL = 'USER_ADS_FAIL';