export const AD_LIST_REQUEST = 'AD_LIST_REQUEST';
export const AD_LIST_SUCCESS = 'AD_LIST_SUCCESS';
export const AD_LIST_FAIL = 'AD_LIST_FAIL';


export const FILTER_BUSINESS_REQUEST = 'FILTER_BUSINESS_REQUEST';
export const FILTER_BUSINESS_SUCCESS = 'FILTER_BUSINESS_SUCCESS';
export const FILTER_BUSINESS_FAIL = 'FILTER_BUSINESS_FAIL';

export const AD_PROFILE_REQUEST = 'AD_PROFILE_REQUEST';
export const AD_PROFILE_SUCCESS = 'AD_PROFILE_SUCCESS';
export const AD_PROFILE_FAIL = 'AD_PROFILE_FAIL';

