export const ARTICLE_LIST_REQUEST = "ARTICLE_LIST_REQUEST";
export const ARTICLE_LIST_SUCCESS = "ARTICLE_LIST_SUCCESS";
export const ARTICLE_LIST_FAIL = "ARTICLE_LIST_FAIL";

export const FILTER_ARTICLE_REQUEST = "FILTER_ARTICLE_REQUEST";
export const FILTER_ARTICLE_SUCCESS = "FILTER_ARTICLE_SUCCESS";
export const FILTER_ARTICLE_FAIL = "FILTER_ARTICLE_FAIL";
