# Pull Docker Hub base image
FROM node:12.2.0-alpine as build
# Set working directory

# Label React PRojected
LABEL version="1.0.0"
LABEL description="REACT FRONTEND FRO The library API"

WORKDIR /usr/src/app
# Install app dependencies

COPY package*.json ./

RUN npm ci

RUN npm install react-scripts@3.0.1 -g --silent
# Copy app to container
COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 3000

RUN npm run build
